public/loader.wasm: src/loader.mjs
src/loader.mjs: src/loader.cpp
    emcc --no-entry src/loader.cpp -o src/loader.mjs  \
      --pre-js src/locateFile.js  \
      -s ENVIRONMENT='web'  \
      -s EXPORT_NAME='createModule'  \
      -s USE_ES6_IMPORT_META=0  \
      -s EXPORTED_FUNCTIONS='["_add", "_matrixMultiply", "_malloc", "_free"]'  \
      -s EXPORTED_RUNTIME_METHODS='["ccall", "cwrap"]'  \
      -O3
    mv src/loader.wasm public/loader.wasm

.PHONY: clean
clean:
    rm public/loader.wasm src/loader.mjs
